from __future__ import annotations

from typing import List, Optional, Protocol

from .entities import PokemonCard


class PokemonCardStoragePort(Protocol):
    async def save(self, card: PokemonCard) -> PokemonCard: ...
    async def get_by_id(self, card_id: int) -> Optional[PokemonCard]: ...
    async def get_all(self) -> List[PokemonCard]: ...
    async def delete(self, card_id: int) -> bool: ...
    async def update(self, card: PokemonCard) -> PokemonCard: ...
