from __future__ import annotations

from typing import Protocol, Optional, List
from .entities import Post


class PostStoragePort(Protocol):
    async def save(self, post: Post) -> Post: ...
    async def get_by_id(self, post_id: int) -> Optional[Post]: ...
    async def get_unposted(self) -> List[Post]: ...
    async def update(self, post: Post) -> Post: ...
